2020-12-15 21:34:35,028 INFO    MainThread:512982 [wandb_init.py:_log_setup():292] Logging user logs to wandb/run-20201215_213435-2ahnpt5g/logs/debug.log
2020-12-15 21:34:35,028 INFO    MainThread:512982 [wandb_init.py:_log_setup():293] Logging internal logs to wandb/run-20201215_213435-2ahnpt5g/logs/debug-internal.log
2020-12-15 21:34:35,028 INFO    MainThread:512982 [wandb_setup.py:_flush():68] setting env: {}
2020-12-15 21:34:35,028 INFO    MainThread:512982 [wandb_setup.py:_flush():68] setting user settings: {}
2020-12-15 21:34:35,028 INFO    MainThread:512982 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-12-15 21:35:22,489 WARNING MainThread:512982 [wandb_init.py:init():483] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 463, in init
    run = wi.init()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 378, in init
    backend.cleanup()
  File "/usr/local/lib/python3.8/dist-packages/wandb/backend/backend.py", line 107, in cleanup
    self.wandb_process.join()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
2020-12-15 21:35:22,503 INFO    MainThread:512982 [internal.py:handle_exit():137] Internal process exited
