Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    train_loader = data_utils.get_dataloader(train_dset, config['batch_size'], config['num_workers'], shuffle=True, weigh=False)
  File "/home/nishant/Desktop/Desktop/Papers2code/Implementations/RotNet-PyTorch/code/data_utils.py", line 82, in get_dataloader
    return DataLoader(dataset, batch_size=batch_size, num_workers=num_workers, shuffle=shuffle, drop_last=drop_last)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 94, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 102, in num_samples
    return len(self.data_source)
  File "/home/nishant/Desktop/Desktop/Papers2code/Implementations/RotNet-PyTorch/code/data_utils.py", line 42, in __len__
    return len(self.train_data)
AttributeError: 'RotnetDataset' object has no attribute 'train_data'
